git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
gui:
  theme:
    activeBorderColor:
      - "#83a598"
      - bold
    inactiveBorderColor:
      - "#504945"
    optionsTextColor:
      - "#d3869b"
    selectedLineBgColor:
      - '#434c5a'
