[manager]
cwd = { fg = "#abb2bf", bg = "reset" }

# Hovered items
hovered = { fg = "#abb2bf", bg = "#3e4451" }
preview_hovered = { fg = "#abb2bf", bg = "#3e4451" }

# Find feature
find_keyword = { fg = "#c678dd", bg = "reset", italic = true }
find_position = { fg = "#61afef", bg = "reset", bold = true }

# Markers
marker_copied = { fg = "#98c379", bg = "reset" }
marker_cut = { fg = "#e06c75", bg = "reset" }
marker_marked = { fg = "#e5c07b", bg = "reset" }
marker_selected = { fg = "#61afef", bg = "reset" }
# marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
# marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
# marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tabs
tab_active = { fg = "#abb2bf", bg = "#3e4451", bold = true }
tab_inactive = { fg = "#5c6370", bg = "#282c34" }
tab_width    = 1

# Status counts
count_copied = { fg = "#98c379", bg = "reset" }
count_cut = { fg = "#e06c75", bg = "reset" }
count_selected = { fg = "#61afef", bg = "reset" }

# Border
border_symbol = "│"
border_style = { fg = "#5c6370", bg = "reset" }

[mode]
# Normal mode
normal_main = { fg = "#000000", bg = "#abb2bf" }
normal_alt = { bg = "#5c6370" }

# Select mode
select_main = { fg = "#000000", bg = "#61afef" }
select_alt = { bg = "#5c6370" }

# Unset mode
unset_main = { fg = "#000000", bg = "#e06c75" }
unset_alt = { bg = "#5c6370" }

[status]
overall = { fg = "#abb2bf", bg = "#282c34" }
separator_open  = ""
separator_close = ""

# Permissions
# perm_type = {}
perm_read = { fg = "#98c379", bg = "reset" }
perm_write = { fg = "#e5c07b", bg = "reset" }
perm_exec = { fg = "#e06c75", bg = "reset" }
perm_sep = { fg = "#5c6370", bg = "reset" }

# Progress
progress_label = { fg = "#abb2bf", bg = "reset" , bold = true}
progress_normal = { fg = "#98c379", bg = "reset" }
progress_error = { fg = "#e06c75", bg = "reset" }

[input]
border = { fg = "#5c6370", bg = "reset" }
title = { fg = "#61afef", bg = "reset", bold = true }
value = { fg = "#abb2bf", bg = "reset" }
selected = { fg = "#abb2bf", bg = "#3e4451" }
# selected = { reversed = true }

[completion]
border = { fg = "#5c6370", bg = "reset" }
active = { fg = "#abb2bf", bg = "#3e4451" }
inactive = { fg = "#5c6370", bg = "reset" }

[tasks]
border = { fg = "#5c6370", bg = "reset" }
title = { fg = "#61afef", bg = "reset", bold = true }
hovered = { fg = "#abb2bf", bg = "#3e4451" }
# hovered = { underline = true }

[which]
cols = 2
mask = { fg = "#282c34", bg = "#282c34" }
cand = { fg = "#98c379", bg = "reset", bold = true }
rest = { fg = "#abb2bf", bg = "reset" }
desc = { fg = "#5c6370", bg = "reset" }
separator = " → "
separator_style = { fg = "#5c6370", bg = "reset" }
# mask            = { bg = "#3c3836" }
# cand            = { fg = "#83a598" }
# rest            = { fg = "#928374" }
# desc            = { fg = "#fe8019" }
# separator_style = { fg = "#504945" }

[help]
on = { fg = "#98c379", bg = "reset", bold = true }
run = { fg = "#61afef", bg = "reset" }
desc = { fg = "#abb2bf", bg = "reset" }
hovered = { fg = "#abb2bf", bg = "#3e4451", bold = true }
footer = { fg = "#5c6370", bg = "reset" }

[notify]
title_info = { fg = "#61afef", bg = "reset", bold = true }
title_warn = { fg = "#e5c07b", bg = "reset", bold = true }
title_error = { fg = "#e06c75", bg = "reset", bold = true }

[filetype]
rules = [
    { mime = "image/*", fg = "#c678dd" },
    { mime = "video/*", fg = "#e5c07b" },
    { mime = "audio/*", fg = "#e5c07b" },
    { mime = "application/zip", fg = "#e06c75" },
    { mime = "application/x-tar", fg = "#e06c75" },
    { mime = "application/x-rar", fg = "#e06c75" },
    { mime = "application/x-gzip", fg = "#e06c75" },
    { mime = "application/x-bzip2", fg = "#e06c75" },
    { mime = "application/pdf", fg = "#e06c75" },
    { mime = "application/json", fg = "#98c379" },
    { mime = "text/*", fg = "#abb2bf" },
    { mime = "inode/directory", fg = "#61afef" },
    { mime = "inode/symlink", fg = "#c678dd" },
    { name = "*", is = "orphan", fg = "#e06c75" },
    { name = "*/", fg = "#61afef" }
]

