-- { "github/copilot.vim" }
return {
  -- {
  --   "zbirenbaum/copilot.lua",
  --   cmd = "Copilot",
  --   -- event = "InsertEnter",
  --   event = "BufReadPost",
  --   -- build = ":Copilot auth",
  --   opts = {
  --     suggestion = {
  --       auto_trigger = true,
  --       keymap = {
  --         accept = "<Tab>",
  --         accept_line = "<M-l>",
  --       },
  --     },
  --   },
  --   config = function(_, opts)
  --     require("copilot").setup(opts)
  --   end,
  -- },
  -- {
  --   "CopilotC-Nvim/CopilotChat.nvim",
  --   dependencies = {
  --     { "zbirenbaum/copilot.lua" },
  --     { "nvim-lua/plenary.nvim", branch = "master" }, -- for curl, log and async functions
  --   },
  --   build = "make tiktoken",                          -- Only on MacOS or Linux
  --   opts = {
  --     -- See Configuration section for options
  --   },
  --   -- See Commands section for default commands if you want to lazy load on them
  -- },
}

-- init = function()
-- vim.api.create_user_command("Copilot", "Toggle Copilot suggestions", function()
--   require("copilot.suggestion").toggle_auto_trigger()
-- end)
-- end,

--   {
--     "<C-a>",
--     function() require("copilot.suggestion").accept() end,
--     mode = { "i" },
--   },
--
-- require("copilot.suggestion").toggle_auto_trigger()

-- {
--   "zbirenbaum/copilot.lua", -- AI programming
--   event = "InsertEnter",
--   keys = {
--     {
--       "<C-a>",
--       function()
--         require("copilot.suggestion").accept()
--       end,
--       desc = "Copilot: Accept suggestion",
--       mode = { "i" },
--     },
--     {
--       "<C-x>",
--       function()
--         require("copilot.suggestion").dismiss()
--       end,
--       desc = "Copilot: Dismiss suggestion",
--       mode = { "i" },
--     },
--     {
--       "<C-\\>",
--       function()
--         require("copilot.panel").open()
--       end,
--       desc = "Copilot: Show panel",
--       mode = { "n", "i" },
--     },
--   },
--   init = function()
--     om.create_user_command("Copilot", "Toggle Copilot suggestions", function()
--       require("copilot.suggestion").toggle_auto_trigger()
--     end)
--   end,
--   opts = {
--     panel = { enabled = false },
--     suggestion = {
--       auto_trigger = true, -- Suggest as we start typing
--       keymap = {
--         accept_word = "<C-l>",
--         accept_line = "<C-j>",
--       },
--     },
--   },
-- },
