return {
  -- "b0o/incline.nvim",
  -- config = function()
  --   local devicons = require("nvim-web-devicons")
  --
  --   require("incline").setup({
  --     window = {
  --       padding = 0,
  --       margin = { horizontal = 0 },
  --     },
  --     hide = {
  --       only_win = true,
  --     },
  --     render = function(props)
  --       local filename = vim.fn.fnamemodify(vim.api.nvim_buf_get_name(props.buf), ":t")
  --       if filename == "" then
  --         filename = "[No Name]"
  --       end
  --       local ft_icon = devicons.get_icon_color(filename)
  --       local modified = vim.bo[props.buf].modified
  --       return {
  --         ft_icon and { ft_icon } or "",
  --         " ",
  --         { filename, gui = modified and "bold,italic" or "bold" },
  --         -- guibg = "#",
  --       }
  --     end,
  --   })
  -- end,
  -- event = "VeryLazy",
}
